const dares = [
  "Sauce Shot Showdown",
  "Tag Along Challenge",
  "Imitation Station",
  "Makeover Mayhem",
  "Campus Catwalk Chronicles",
  "Meme Moves Madness",
  "Object of Affection",
  "Strength Showdown",
  "Senior Surprise Call",
  "Foam Face Freeze",
  "Search Secrets Exposed",
  "Social Media Shuffle",
  "Text Reveal Roulette",
  "Insta Feed Flash",
  "Talent Spotlight Showdown",
  "Doodle Face Frenzy",
  "Standup comedy",
  "Jump & Jingle Jamboree",
  "Backwards Fashion Forward",
  "Style Swap Surprise",
  "Stare Down",
  "Skribbling",
  "Push-Up Power Play",
  "Dance Chain Challenge",
  "Needle Thread Sprint",
  "Pen Ball Relay",
  "Water Mouth Challenge",
];

export default dares;