const dares = [
  "Chug on hot sauce shots.(Sauce Shot Showdown)",
  "Carry the tags provided by the MLSC team throughout the designated time",
  "Do a funny mimicry of any iconic youtuber/creator",
  "Our team would do the makeup of one of your teammates",
  "Recreate the most iconic walk you have observed on campus",
  "Groove on meme songs",
  "Flirt with any object given by the MLSC team",
  "Arm/Leg wrestling for girls/boys",
  "Prank call to a senior(senior to be chosen by taking a chit from a bowl)",
  "Put shaving cream on your face for a certain time",
  "Let the audience see your top 20 browser searches",
  "Choose between three of your teammates who you would follow, block and have in close friends",
  "Show your recent texts",
  "Present your insta feed to the audience",
  "Showcase your talent to judges",
  "Permanent marker face doodle",
  "Standup comedy",
  "Sing a song while doing jumping jacks",
  "Wear Clothes Backwards: Put on an item of clothing backward for the next hour",
  "Let someone else style your hair. Keep it that way for the rest of the event",
  "Have a staring contest",
  "Play a skribble match",
  "Push-up contest",
  "Perform chain reaction(dance each player has to perform for at least 10 seconds and the last step to be performed again when a new player starts)",
  "Insert a thread in the needle in the least amount of time",
  "Players must pick up a ball with 2 pens and carry it across the stage without dropping it otherwise they restart",
  "1 team member fills their mouth with water. try not to spit it out. Face off(opponent team tries to make the person with mouth full of water laugh)",
];

export default dares;