const questions = [
  {//0
    no: 0,
    q: null,
    a: "The dolphin and the shark",
    keyword: 'The dolphin and the shark question',
    imagepath: 'assets/images/questions/q2.jpg',
    audiopath: 'assets/audios/q2.mp3',
    videopath: null,
    score: 0,
  },
  {//1
    no: 1,
    q: "What colour is you MLSC?",
    a: "Knight",
    imagepath: 'assets/images/questions/q1.jpg',
    audiopath: null,
    videopath: null,
    score: 7,
  },
  {//2
    no: 2,
    q: null,
    a: 'Elizabeth tower',
    keyword: 'Elizabeth tower',
    imagepath: 'assets/images/questions/q7.jpg',
    audiopath: null,
    videopath: null,
    score: 7,
  },
  {//3
    no: 3,
    q: 'Check his Audacity👇',
    a: 'DG IMMORTALS',
    keyword: 'Systumm question',
    imagepath: 'assets/images/questions/q4.jpg',
    audiopath: 'assets/audios/q4.mp3',
    videopath: null,
    score: 7,
  },
  {//4
    no: 4,
    q: '⠞⠗⠁⠝⠎⠇⠁⠞⠑ Lord Mellstroy',
    a: "Mango",
    imagepath: 'assets/images/questions/q5.jpg',
    audiopath: null,
    videopath: null,
    score: 10,
  },
  {//5
    no: 5,
    q: '“Huh, a pigeon?”',
    a: "The Brave Fighter of Sun Fighbird",
    imagepath: 'assets/images/questions/q6.jpg',
    audiopath: null,
    videopath: null,
    score: 10,
  },
  {//6
    no: 6,
    q: '15xx 18xx<br>“Can we do something about it?”',
    a: "JMW TURNER",
    imagepath: null,
    audiopath: null,
    videopath: null,
    score: 10,
  },
  {//7
    no: 7,
    q: 'Guess his favourite lnmsg',
    a: 'August',
    imagepath: 'assets/images/questions/q8.jpg',
    audiopath: null,
    videopath: null,
    score: 15,
  },
  {//8
    no: 8,
    q: '! moj krdii vhaa bete vhaa tum toh bde heavy driver ho',
    a: "Chalk",
    imagepath: null,
    audiopath: null,
    videopath: null,
    score: 15,
  },
  {//9
    no: 9,
    q: null,
    a: 'Amphiprioninae',
    keyword: 'mirror nemo question',
    imagepath: 'assets/images/questions/q10.jpg',
    audiopath: null,
    videopath: null,
    score: 15,
  },
  {//10
    no: 10,
    q: "Pigeon Pigeon on the wall",
    a: 'london guildhall',
    keyword: 'pigeon cipher question',
    imagepath: 'assets/images/questions/q11.jpg',
    audiopath: null,
    videopath: null,
    score: 20,
  },
  {//11
    no: 11,
    q: null,
    a: 'Galileo Galilei',
    keyword: 'Galileo Galilei question',
    imagepath: 'assets/images/questions/q12.jpg',
    audiopath: null,
    videopath: null,
    score: 20,
  },
  {//12
    no: 12,
    q: '"Agaya mera paisa leke?"<br>"Babu Bhaiya se direct Babu!?"<br>Answer Format: <b>xxxx</b><i>px</i> <b>xxxx</b><i>deg</i>',
    a: '2520px 150deg',
    imagepath: 'assets/images/questions/q13.jpg',
    audiopath: null,
    videopath: null,
    score: 30,
  },
  {//13
    no: 13,
    q: null,
    a: 'Grace Hopper',
    keyword: 'Grace Hopper question',
    imagepath: 'assets/images/questions/q14.jpg',
    audiopath: null,
    videopath: null,
    score: 40,
  },
  {//14
    no: 14,
    q: 'FFG3BBI3ABGH(Шестиричная система ↑↓)',
    a: 'Whenever you need somebody',
    imagepath: null,
    audiopath: null,
    videopath: null,
    score: 50,
  },
];

export default questions;