const questions = [
  {//0
    q: "Demo Question",
    a: "Demo Answer",
    imagepath: 'assets/images/questions/demo1.png',
    audiopath: null,
    videopath: null,
    score: 0,
  },
  {//1
    q: "What colour is you MLSC?",
    a: "Knight",
    imagepath: 'assets/images/questions/q1.jpg',
    audiopath: null,
    videopath: null,
    score: 5,
  },
  {//2
    q: null,
    a: "The dolphin and the shark",
    keyword: 'The dolphin and the shark question',
    imagepath: 'assets/images/questions/q2.jpg',
    audiopath: 'assets/audios/q2.mp3',
    videopath: null,
    score: 5,
  },
  {//3
    q: '15xx 18xx<br>“Can we do something about it?”',
    a: "JMW TURNER",
    imagepath: null,
    audiopath: null,
    videopath: null,
    score: 5,
  },
  {//4
    q: null,
    a: 'DG IMMORTALS',
    keyword: 'Systumm question',
    imagepath: 'assets/images/questions/q4.jpg',
    audiopath: 'assets/audios/q4.mp3',
    videopath: null,
    score: 5,
  },
  {//5
    q: '⠞⠗⠁⠝⠎⠇⠁⠞⠑ Lord Mellstroy',
    a: "Mango",
    imagepath: 'assets/images/questions/q5.jpg',
    audiopath: null,
    videopath: null,
    score: 5,
  },
  {//6
    q: '“Huh, a pigeon?”',
    a: "The Brave Fighter of Sun Fighbird",
    imagepath: 'assets/images/questions/q6.jpg',
    audiopath: null,
    videopath: null,
    score: 5,
  },
  {//7
    q: null,
    a: 'Elizabeth tower',
    keyword: 'Elizabeth tower',
    imagepath: 'assets/images/questions/q7.jpg',
    audiopath: null,
    videopath: null,
    score: 5,
  },
  {//8
    q: 'Guess his favourite lnmsg',
    a: 'August',
    imagepath: 'assets/images/questions/q8.jpg',
    audiopath: null,
    videopath: null,
    score: 5,
  },
  {//9
    q: '! moj krdii vhaa bete vhaa tum toh bde heavy driver ho',
    a: "Chalk",
    imagepath: null,
    audiopath: null,
    videopath: null,
    score: 5,
  },
  {//10
    q: null,
    a: 'Amphiprioninae',
    keyword: 'mirror nemo question',
    imagepath: 'assets/images/questions/q10.jpg',
    audiopath: null,
    videopath: null,
    score: 5,
  },
  {//11
    q: null,
    a: 'london guildhall',
    keyword: 'pigeon cipher question',
    imagepath: 'assets/images/questions/q11.jpg',
    audiopath: null,
    videopath: null,
    score: 5,
  },
  {//12
    q: null,
    a: 'Galileo Galilei',
    keyword: 'Galileo Galilei question',
    imagepath: 'assets/images/questions/q12.jpg',
    audiopath: null,
    videopath: null,
    score: 5,
  },
  {//13
    q: '"Agaya mera paisa leke?"<br>"Babu Bhaiya se direct Babu!?"<br>Answer Format: <b>xxxx</b><i>px</i> <b>xxxx</b><i>deg</i>',
    a: '2520px 150deg',
    imagepath: 'assets/images/questions/q13.jpg',
    audiopath: null,
    videopath: null,
    score: 5,
  },
  {//14
    q: null,
    a: 'Grace Hopper',
    keyword: 'Grace Hopper question',
    imagepath: 'assets/images/questions/q14.jpg',
    audiopath: null,
    videopath: null,
    score: 5,
  },
  {//15
    q: 'FFG3BBI3ABGH(Шестиричная система ↑↓)',
    a: 'Whenever you need somebody',
    imagepath: null,
    audiopath: null,
    videopath: null,
    score: 5,
  },
];

export default questions;